// <auto-generated />
using System;
using DugnadAppMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DugnadAppMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260728143054_AddFellesDugnad")]
    partial class AddFellesDugnad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DugnadAppMvc.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Beboer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeilighetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Epost")
                        .IsUnique();

                    b.HasIndex("LeilighetId");

                    b.ToTable("Beboere");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Dugnad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<bool>("ErSynlig")
                        .HasColumnType("boolean");

                    b.Property<bool>("KreverPamelding")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaksAntallDeltakere")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SluttDato")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDato")
                        .HasColumnType("date");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dugnader");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Dugnadstime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeboerId")
                        .HasColumnType("integer");

                    b.Property<int>("DugnadId")
                        .HasColumnType("integer");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Registrert")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Timer")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BeboerId");

                    b.HasIndex("DugnadId");

                    b.ToTable("Dugnadstimer");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.FellesDugnad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("ErAvlyst")
                        .HasColumnType("boolean");

                    b.Property<string>("Oppmotested")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SluttTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FellesDugnader");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Innstillinger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dugnadsbudsjett")
                        .HasColumnType("integer");

                    b.Property<string>("SameieNavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Innstillinger");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Leilighet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Leilighetsnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seksjonsnummer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Seksjonsnummer")
                        .IsUnique();

                    b.ToTable("Leiligheter");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Oppgave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AntallPersoner")
                        .HasColumnType("integer");

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("ErUtført")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FraDato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Frist")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("KanRegistrereTimer")
                        .HasColumnType("boolean");

                    b.Property<bool>("KreverBekreftelse")
                        .HasColumnType("boolean");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Opprettet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpprettetAvId")
                        .HasColumnType("text");

                    b.Property<int>("Prioritet")
                        .HasColumnType("integer");

                    b.Property<string>("Utstyr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UtstyrPlassering")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OpprettetAvId");

                    b.ToTable("Oppgaver");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.OppgavePamelding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeboerId")
                        .HasColumnType("integer");

                    b.Property<int>("OppgaveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PameldtDato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UtfortDato")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeboerId");

                    b.HasIndex("OppgaveId");

                    b.ToTable("OppgavePamelding", (string)null);
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Sameie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Sameier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Timeforing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AntallTimer")
                        .HasColumnType("numeric");

                    b.Property<int>("BeboerId")
                        .HasColumnType("integer");

                    b.Property<int?>("DugnadId")
                        .HasColumnType("integer");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<int?>("OppgaveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistrertDato")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BeboerId");

                    b.HasIndex("DugnadId");

                    b.HasIndex("OppgaveId");

                    b.ToTable("Timeforinger");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Beboer", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DugnadAppMvc.Models.Leilighet", "Leilighet")
                        .WithMany("Beboere")
                        .HasForeignKey("LeilighetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Leilighet");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Dugnadstime", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.Beboer", "Beboer")
                        .WithMany("Dugnadstimer")
                        .HasForeignKey("BeboerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DugnadAppMvc.Models.Dugnad", "Dugnad")
                        .WithMany("Dugnadstimer")
                        .HasForeignKey("DugnadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beboer");

                    b.Navigation("Dugnad");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Oppgave", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.ApplicationUser", "OpprettetAv")
                        .WithMany()
                        .HasForeignKey("OpprettetAvId");

                    b.Navigation("OpprettetAv");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.OppgavePamelding", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.Beboer", "Beboer")
                        .WithMany("OppgavePameldinger")
                        .HasForeignKey("BeboerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DugnadAppMvc.Models.Oppgave", "Oppgave")
                        .WithMany("Pameldinger")
                        .HasForeignKey("OppgaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beboer");

                    b.Navigation("Oppgave");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DugnadAppMvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Timeforing", b =>
                {
                    b.HasOne("DugnadAppMvc.Models.Beboer", "Beboer")
                        .WithMany()
                        .HasForeignKey("BeboerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DugnadAppMvc.Models.Dugnad", "Dugnad")
                        .WithMany()
                        .HasForeignKey("DugnadId");

                    b.HasOne("DugnadAppMvc.Models.Oppgave", "Oppgave")
                        .WithMany()
                        .HasForeignKey("OppgaveId");

                    b.Navigation("Beboer");

                    b.Navigation("Dugnad");

                    b.Navigation("Oppgave");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Beboer", b =>
                {
                    b.Navigation("Dugnadstimer");

                    b.Navigation("OppgavePameldinger");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Dugnad", b =>
                {
                    b.Navigation("Dugnadstimer");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Leilighet", b =>
                {
                    b.Navigation("Beboere");
                });

            modelBuilder.Entity("DugnadAppMvc.Models.Oppgave", b =>
                {
                    b.Navigation("Pameldinger");
                });
#pragma warning restore 612, 618
        }
    }
}
